name: info_plus
description: "Info Plus is flutter package to display an animated alert , warning, succes or error message from the top or bottom"
version: 0.0.1
homepage: https://github.com/moeed366/info_plus
repository: https://github.com/moeed366/info_plus
screenshots:
  - description: "Screenshot for different type of info plus"
    path: example/assets/screenshots/alert_pro_image.png
topics:
  - snackbar
  - toast
  - message
  - alert

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
